### ISSUE TITLE
New argument to include the blunder move or not

### ISSUE THREAD

**Issue by vitogit** [vitogit/pgn-tactics-generator#16]
As @karol-brejna-i said here https://github.com/vitogit/pgn-tactics-generator/issues/5#issuecomment-812339311 some sites start with the blunder move like chess.com and others starts directly with the puzzle to solve with the blunder already in the position.

Currently the puzzle generator includes the opponent blunder move. 

So my idea is to have a new argument called `--includeBlunder` with a default value of `true` but you can set it to `false`  to not include the blunder move and have the position with the blunder already there.

**Comment by karol-brejna-i** [comment]
I am on it.

**Comment by karol-brejna-i** [comment]
I think we can close this one.

**Comment by vitogit** [comment]
Cool, thanks!
