### ISSUE TITLE
python-chess breaking the code

### ISSUE THREAD

**Issue by AbinGibiAbin** [vitogit/pgn-tactics-generator#2]
python-chess library is updated without backwards compatibility and the code won't work anymore. Seems they replaced chess.uci with chess.engine however the implementation of chess.engine is quite different so your code needs to be updated.

**Comment by vitogit** [comment]
Thanks @AbinGibiAbin the supported versions are in the requirements.txt
python-chess==0.15.0
requests==2.20.0
Is it working for you if you use those versions?

Anyway I think it will make sense to update those versions and the code to work with the last stable version of python-chess

**Comment by vitogit** [comment]
I updated the readme to make it clear that the best way to install this is to use the requirements.txt. Like this:  `pip3 install -r requirements.txt --user`

Also I updated the requirement python-chess version to `python-chess==0.24.2` is the one before the breaking change.

Currently updating the code to support the last version of python-chess is not in my plan
