### ISSUE TITLE
Support for Custom Stockfish Binary Path

### ISSUE THREAD

**Issue by meetusadadiya** [vitogit/pgn-tactics-generator#23]
Hi there! This tool seems to be useful but the problem is it may not work in Apple M1 chips as it is using lichess's fork of Stockfish. Can you add an option to set a custom path for Stockfish-binary in CLI arguments?

**Comment by vitogit** [comment]
Hi, I don't have much time (or an Apple M1) but I will add some info in case you or someone else want to do a PR. 

The program will try to update stockfish when calling the engine https://github.com/vitogit/pgn-tactics-generator/blob/137cca2bece85c1539762f242a7fa543f006e4b9/modules/fishnet/fishnet.py#L31
update=True

and it will look for a binary using this name format https://github.com/vitogit/pgn-tactics-generator/blob/137cca2bece85c1539762f242a7fa543f006e4b9/modules/fishnet/fishnet.py#L40 

New arguments are added here https://github.com/vitogit/pgn-tactics-generator/blob/master/main.py#L30

So I think those are the places that needs to be updated if the program uses a specific local stockfish

**Comment by karol-brejna-i** [comment]
@meetusadadiya could you describe how you obtain stockfish binaries for your Mac? I’ll try to reproduce and think of additional config switches

**Comment by meetusadadiya** [comment]
I just clone `https://github.com/official-stockfish/Stockfish/` repo and build the source code.
I use following flags in make command:
`make -j2 build ARCH=apple-silicon`

**Comment by karol-brejna-i** [comment]
@meetusadadiya While I am waiting to get my hands on MacBook to test the code, you could try running the code from https://github.com/karol-brejna-i/pgn-tactics-generator/tree/stockfish-path -- if you want to.
It introduces the `--stockfhish` command line parameter to give the path to your stockfish binary.

**Comment by meetusadadiya** [comment]
@karol-brejna-i Yeah, I've tried it, It works completely fine.

**Comment by karol-brejna-i** [comment]
I’ve also updated build-stockfish.sh to include apple silicon. I’ll issue a PR.
