### ISSUE TITLE
invalid result?

### ISSUE THREAD

**Issue by abjunk07** [vitogit/pgn-tactics-generator#5]
[Event "0728 03099"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "solver"]
[Black "?"]
[Result "*"][SetUp "1"]
[FEN "3r3k/6pp/3Q4/q7/8/4P2P/6P1/5RK1 b KQkq - 0 1"]

1...Rxd6 2.Rf8# *

several issues here:
1. invalid tag [Result "*"][SetUp "1"]
2. invalid result, must be 1-0
3. what kind of puzzle is it? While blunder? Does it mean that the 1st move is always a wrong one?
In the referred https://github.com/xinyangz/chess-tactics-pgn/ I see these kinds of 'puzzles' along with the right ones, when whoever does the 1st move wins. The guy claims that his puzzles are generated by your program, so how do I distinguish which are which?

**Comment by karol-brejna-i** [comment]
I must admit, for me, it's a bit strange to start the game with the blunder (the tactics files I used to have were all started with the move of the winning side).  On the other hand, I noticed, it's quite a common approach. You can find this kind of puzzle on chess.com, for example...

@vitogit Maybe we should allow the user to decide if he wants to include the first move (blunder) into the results -- with a command-line switch, or sth.

**Comment by vitogit** [comment]
Totally ok with a new flag called includeBlunderMove with a default `true` value and if you want you can just set it to `false`

**Comment by vitogit** [comment]
I will close this issue and openend a new one to clarify the idea @karol-brejna-i  https://github.com/vitogit/pgn-tactics-generator/issues/16
