### ISSUE TITLE
Any plans to merge https://github.com/lazydroid/pgn-tactics-generator?

### ISSUE THREAD

**Issue by karol-brejna-i** [vitogit/pgn-tactics-generator#6]
Are aware of this fork? Do you plan to merge some changes from the other repo?

I was thinking about using pgn-tactics-generator, do some code cleanup, etc. so I wanted to know just in case...

**Comment by vitogit** [comment]
Hi @karol-brejna-i no I don't plan to merge changes.

**Comment by vitogit** [comment]
Also if you want take a look at this fork seems to be well developed https://github.com/linrock/chess-puzzle-maker

**Comment by karol-brejna-i** [comment]
Thx
