### ISSUE TITLE
Unknown class ConfigError in fishnet.py

### ISSUE THREAD

**Issue by karol-brejna-i** [vitogit/pgn-tactics-generator#9]
See: https://github.com/lazydroid/pgn-tactics-generator/blob/master/modules/fishnet/fishnet.py#L90

It looks like we lack a definition for the class ConfigError

Unless there was some "special" logic planned for the class, this simple addition would fix the issue:

```python

class ConfigError(Error):
    """Error in configuration."""
```

Let me know if it is ok.

**Comment by vitogit** [comment]
Yes I think you are right and the solution is good for our usecase.

**Comment by vitogit** [comment]
Fixed by https://github.com/vitogit/pgn-tactics-generator/pull/13
